[package]
name = "rdb-mcp"
version.workspace = true
edition.workspace = true
description = "MCP server to access Relational Database over stdio."
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
rdb-mcp-core.workspace = true
rmcp = { workspace = true, features = ["transport-io"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
